### PR TITLE
Supported requests with chunked `Transfer-Encoding`

### PR DESCRIPTION
**Pull request by ueffel**
I am using this plugin to serve some git repositories via `git-http-backend`. It works very well.

The only thing that does not work is if you `git push` something that is bigger than the [`http.postBuffer`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httppostBuffer). The push fails like this:

```shell
$ git push test
Enumerating objects: 709, done.
Counting objects: 100% (709/709), done.
Delta compression using up to 16 threads
Compressing objects: 100% (702/702), done.
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (709/709), 33.68 MiB | 211.61 MiB/s, done.
Total 709 (delta 7), reused 709 (delta 7), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

The reason is `git`'s handling of big pushes:

> Maximum size in bytes of the buffer used by smart HTTP transports when POSTing data to the remote system. For requests larger than this buffer size, HTTP/1.1 and Transfer-Encoding: chunked is used to avoid creating a massive pack file locally. Default is 1 MiB, which is sufficient for most requests.

The Go CGIHandler (which this plugin is using) just refuses to handle chunked transfers <https://github.com/golang/go/blob/go1.18.3/src/net/http/cgi/host.go#L122-L126>.

-----

To work around this issue this pull request adds buffering of these chunked requests before giving it to the CGI application.  
Requests are buffered in memory or in a temporary file depending on the size and the correct `CONTENT-LENGTH` is set. The threshold when to buffer in memory or in a temporary file is configurable via a new `buffer_limit` settings which defaults to `4MiB` if not specified.

Additional things:

* Add logging of `Stderr` from the CGI application to caddy's log
* Fix some markdown lint warnings in the `doc/document.md` and recreate `doc.go` and `README.md` with the Makefile
* small code cleanups

### CODE REVIEW

**Comment by ueffel** [comment]
@aksdb ping

**Comment by aksdb** [comment]
> @aksdb ping

Dammit, missed the PR notification. I'll review it tomorrow. Thanks for the ping and sorry for having missed it till now!

**Comment by ueffel** [comment]
> > @aksdb ping
> 
> Dammit, missed the PR notification. I'll review it tomorrow. Thanks for the ping and sorry for having missed it till now!

you aren't watch this repository, i think you didn't even get a notification

**Review by aksdb — APPROVED** [review]
LGTM. Very nice additions and cleanups. Thanks you very much!

**Pull request merged**
